### ISSUE TITLE
new agent causes crash on old server.

### ISSUE THREAD

**Issue by igable** [hep-gc/shoal#84] opened 2015-03-10 23:40 UTC
When starting an agent from Amazon the config was that we had this morning we can actually trigger a crash of the shoal server:

`
2015-03-10 16:29:22,267 - ERROR - [shoal.py:113] - <RabbitMQConsumer(Thread-2, stopped daemon 140350903142144)> died. Stopping application...
`

Going to look for the crash causing config now.

**Comment by colsond** [comment] 2015-03-11 15:24
I believe this is a bug caused by an agent that does not send a public ip, Ron and I found this bug late last week and I have pushed the patch to master already. Shoal gets confused when there is a "None":

`2015-03-10 15:42:25,350 - ERROR - [utilities.py:29] - inet_aton() argument 1 must be string, not None
2015-03-10 15:42:25,352 - INFO - [connectionpool.py:180] - Starting new HTTP connection (1): None
2015-03-10 15:42:25,354 - INFO - [utilities.py:259] - Timeout or proxy error, blacklisting:None
`

This should be fixed with [this commit](https://github.com/hep-gc/shoal/commit/d26853f962273b8c7e9d086fbfd6f072f5024155).

**Comment by colsond** [comment] 2015-03-11 20:30
One log string was missed in the previous commit but has been fixed in this [here](https://github.com/hep-gc/shoal/commit/5d8dd8b709dbb04c18dbf41c90df64fbabab3a68). Issues like these make it clear that shoal needs a stronger test suite to ensure bugs like these do not make it into a production environment.

**Closed by colsond** 2015-03-11 20:30 UTC
